name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [feed-service, user-service]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.24.3

    - name: Install dependencies
      working-directory: ${{ matrix.service }}
      run: go mod download

    - name: Run tests
      working-directory: ${{ matrix.service }}
      run: make test
